language: java
jdk: oraclejdk8
before_install: chmod +x mvnw
script: mvn verify
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_KEY
  app: budincsevity-opensubtitles-api
notifications:
  email: nbudincsevity@gmail.com
